development: &development
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: bliweb_dev

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: bliweb_test

production: &production
  adapter: mysql2
  host: localhost
  database: bliweb_production
  username: your_production_database_login
  password: your_production_database_password
